[package]
name = "segsource"
version = "0.1.0"
authors = [ "Brendan McGloin <stmonkeydoom@gmail.com>",]
edition = "2018"
license = "MIT"
description = "A helper library to make reading data more pleasant."
homepage = "https://github.com/russells-crockpot/segsource"
repository = "https://github.com/russells-crockpot/segsource"
readme = "../README.md"
documentation = "https://docs.rs/segsource/"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bytes = { version = "1.0", optional = true}
thiserror = "1.0"
tokio = { version = "1.7", optional = true, features = ["fs", "io-util", "rt"]}
bitvec = { version = "0.19", optional = true }
async-trait = { version = "0.1.50", optional = true }
pin-project-lite = { version = "0.2.6", optional = true }
futures-core = { version = "0.3.15", optional = true }
scroll = { version = "0.10.2", optional = true }

[features]
default = []
memmap = [ "fs3", "memmap2",]
async = ["tokio", "async-trait", "pin-project-lite", "futures-core"]

[dependencies.fs3]
version = "0.5"
optional = true

[dependencies.memmap2]
version = "0.3"
optional = true

[dependencies.segsource-macros]
path = "../macros"
version = "0.1.0"

#[dependencies.here]
#path = "../../here"
#version = "1.0.0"
#features = ["log"]
